---
  - hosts: 127.0.0.1
    connection: local

    vars:
      dev_env_dir: /opt/startupper

    tasks:
      - name: Install AWS cli
        community.general.homebrew:
          name:
            - awscli
          state: present

      - name: Install Google cloud sdk
        community.general.homebrew_cask:
          name: google-cloud-sdk
          state: present

      - name: Install development packages
        community.general.homebrew:
          name:
            - node
            - yarn
            - yarn-completion
            - php
            - golang
            - python@3.10
          state: present

      - name: Install system packages from cask
        community.general.homebrew_cask:
          name:
            - iterm2
            - visual-studio-code
            - postman
          state: present
      
      - name: Install db programs
        community.general.homebrew_cask:
          name:
            - dbeaver-community
            - openrefine
          state: present
