---
  - hosts: 127.0.0.1
    connection: local

    vars:
      dev_env_dir: /opt/startupper

    tasks:
      - name: Install general programs
        community.general.homebrew_cask:
          name:
            - slack
            - google-chrome
            - firefox
            - bitwarden
            - miro
            - hot
            - clickup
          state: present
