---
  - hosts: 127.0.0.1
    connection: local
    become: true
    become_user: root

  - name: Importing DEVELOPER playbook for linux
    import_playbook: linux/developer.yml
    when: ansible_distribution_major_version|int >= 18 and userType == "developer"

  - name: Importing ANALYST playbook for linux
    import_playbook: linux/analyst.yml
    when: ansible_distribution_major_version|int >= 18 and userType == "analyst"

  - name: Importing DESIGNER playbook for linux
    import_playbook: linux/designer.yml
    when: ansible_distribution_major_version|int >= 18 and userType == "designer"

  - name: Importing IT playbook for linux
    import_playbook: linux/it.yml
    when: ansible_distribution_major_version|int >= 18 and userType == "it"

